# Generated by Django 4.2.1 on 2024-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_reserva', models.IntegerField()),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=50)),
                ('correo', models.EmailField(help_text='Ingrese Correo', max_length=254)),
                ('fecha', models.DateField(help_text='Ingrese fecha')),
                ('hora', models.IntegerField(help_text='Ingrese hora')),
                ('cantidad_comensales', models.IntegerField(help_text='Ingrese cantidad de comensales')),
            ],
        ),
    ]
