# Generated by Django 4.2.1 on 2024-04-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_mesa_reserva_mesa_id_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_mesa',
            name='hora',
            field=models.TimeField(help_text='Ingrese hora'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('ID_Pedido', models.IntegerField(help_text='Id del pedido', primary_key=True, serialize=False)),
                ('Estado', models.CharField(help_text='Estado en el cual se encuentra el pedido', max_length=20)),
                ('Correo_Sol', models.EmailField(help_text='Correo electronico del usuario', max_length=254)),
                ('ID_Mesa', models.ForeignKey(help_text='Id de la mesa', on_delete=django.db.models.deletion.CASCADE, to='appweb.mesa')),
            ],
        ),
    ]
