# Generated by Django 4.2.1 on 2024-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_alter_reserva_mesa_hora_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('ID_Ingrediente', models.IntegerField(help_text='Id del ingrediente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='nombre del ingrediente', max_length=50)),
                ('Costo', models.IntegerField(help_text='Valor del ingrediente')),
                ('unidad_medida', models.CharField(help_text='Unidad de medida del ingrediente', max_length=4)),
            ],
        ),
    ]
