# Generated by Django 4.2.1 on 2024-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('ID_Plato', models.IntegerField(help_text='Id del plato', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(help_text='Nombre del plato', max_length=50)),
                ('Costo', models.IntegerField(help_text='Valor del plato')),
                ('Region', models.CharField(help_text='Región a la cual pertenece el plato', max_length=50)),
                ('Cantidad_Comensales', models.IntegerField(help_text='Cantidad de personas que pueden comer de este plato')),
                ('Descripcion', models.TextField(help_text='Breve descripción del plato', max_length=200)),
            ],
        ),
    ]
