# Generated by Django 4.2.1 on 2024-04-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripción_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costo', models.IntegerField(help_text='Valor total del pedido')),
                ('ID_Pedido', models.ForeignKey(help_text='Id de pedido', on_delete=django.db.models.deletion.CASCADE, to='appweb.pedidos')),
                ('ID_Platos', models.ForeignKey(help_text='Id del plato', on_delete=django.db.models.deletion.CASCADE, to='appweb.platos')),
            ],
        ),
    ]
