# Generated by Django 4.2.1 on 2024-04-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_descripción_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletas',
            fields=[
                ('ID_Boleta', models.IntegerField(help_text='Id de la boleta', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(help_text='Fecha de emision de la boleta')),
                ('Costo_Total', models.IntegerField(help_text='Valor total de atención')),
                ('ID_Pedido', models.ForeignKey(help_text='Id del pedido', on_delete=django.db.models.deletion.CASCADE, to='appweb.pedidos')),
            ],
        ),
    ]
