# Generated by Django 4.2.1 on 2024-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_boletas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Rut', models.CharField(help_text='Rut usuario', max_length=15, primary_key=True, serialize=False)),
                ('Correo', models.EmailField(help_text='Correo electronico del usuario', max_length=254, unique=True)),
                ('Nombre', models.CharField(help_text='Nombre del usuario', max_length=50)),
                ('Direccion', models.CharField(help_text='Dirección del usuario', max_length=100)),
                ('Telefono', models.IntegerField(help_text='Numero telefonico del usuario')),
                ('Contraseña', models.IntegerField(help_text='Contraseña del usuario')),
                ('Tipo_Usuario', models.CharField(help_text='Tipo de usuario', max_length=20)),
            ],
        ),
    ]
