# Generated by Django 4.2.1 on 2024-05-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_alter_platos_cantidad_comensales_alter_platos_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_mesa',
            name='ID_Mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.mesa'),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='cantidad_comensales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
