# Generated by Django 4.2.1 on 2024-05-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_alter_reserva_mesa_id_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_mesa',
            name='id',
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='ID_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
