# Generated by Django 4.2.1 on 2024-05-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0014_remove_reserva_mesa_id_alter_reserva_mesa_id_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_mesa',
            name='ID_Mesa',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appweb.mesa'),
        ),
    ]
