# Generated by Django 4.2.1 on 2024-05-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_alter_reserva_mesa_id_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ID_Ing_Bod',
            field=models.AutoField(help_text='Id del ingrediente en la bodega', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='ID_Boleta',
            field=models.AutoField(help_text='Id de la boleta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='ID_Ingrediente',
            field=models.AutoField(help_text='Id del ingrediente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='ID_Mesa',
            field=models.AutoField(help_text='Id de la mesa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ID_Pedido',
            field=models.AutoField(help_text='Id del pedido', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platos',
            name='ID_Plato',
            field=models.AutoField(help_text='Id del plato', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ID_Ingrediente_Receta',
            field=models.AutoField(help_text='Id del ingrediente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='ID_Mesa',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='appweb.mesa'),
        ),
        migrations.AlterField(
            model_name='reserva_mesa',
            name='ID_reserva',
            field=models.AutoField(help_text='Id de la reserva', primary_key=True, serialize=False),
        ),
    ]
