# Generated by Django 4.2.1 on 2024-05-05 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_alter_bodega_id_ing_bod_alter_boletas_id_boleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sol_Ingredientes',
            fields=[
                ('ID_Solicitud_Ingrediente', models.AutoField(help_text='Id de la solicitud', primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(help_text='Cantidad solicitada')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ingrediente', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='appweb.ingredientes')),
            ],
        ),
    ]
