# Generated by Django 4.2.1 on 2024-05-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0017_sol_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='Disponibilidad',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
