# Generated by Django 4.2.1 on 2024-05-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0022_sol_ingredientes_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Correo_Sol',
            field=models.EmailField(help_text='Correo electronico del usuario', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Estado',
            field=models.CharField(default='Sin Solicitud', help_text='Estado en el cual se encuentra el pedido', max_length=20),
        ),
    ]
