# Generated by Django 4.2.1 on 2024-05-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_alter_pedidos_correo_sol_alter_pedidos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletas',
            name='ID_Pedido',
        ),
        migrations.RemoveField(
            model_name='descripción_pedidos',
            name='id',
        ),
        migrations.AddField(
            model_name='boletas',
            name='ID_Mesa',
            field=models.ForeignKey(default=1, help_text='Id del pedido', on_delete=django.db.models.deletion.CASCADE, to='appweb.mesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descripción_pedidos',
            name='Listo',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='descripción_pedidos',
            name='Sol_cocina',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Descripción_Pedidos_Historico',
            fields=[
                ('ID', models.AutoField(help_text='Id', primary_key=True, serialize=False)),
                ('Costo', models.IntegerField(help_text='Valor total del pedido')),
                ('ID_Boleta', models.ForeignKey(help_text='Id de la Boleta', on_delete=django.db.models.deletion.CASCADE, to='appweb.boletas')),
                ('ID_Platos', models.ForeignKey(help_text='Id del plato', on_delete=django.db.models.deletion.CASCADE, to='appweb.platos')),
            ],
        ),
        migrations.AddField(
            model_name='descripción_pedidos',
            name='ID',
            field=models.AutoField(default=0, help_text='Id', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
