# Generated by Django 4.2.1 on 2024-05-25 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0024_remove_boletas_id_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='Fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
