# Generated by Django 4.2.1 on 2024-05-26 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0025_alter_boletas_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('ID_Carrito', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Completado', models.BooleanField(default=False)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.PositiveBigIntegerField(default=0)),
                ('PlatoC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Platos', to='appweb.platos')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlatosCarrito', to='appweb.carrito')),
            ],
        ),
    ]
