# Generated by Django 4.2.1 on 2024-06-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0026_carrito_platocarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platocarrito',
            name='PlatoC',
        ),
        migrations.RemoveField(
            model_name='platocarrito',
            name='carrito',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='PlatoCarrito',
        ),
    ]
