# Generated by Django 4.2.1 on 2024-06-12 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0027_remove_platocarrito_platoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripción_pedidos_historico',
            name='fecha_y_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
