# Generated by Django 4.2.1 on 2024-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0028_descripción_pedidos_historico_fecha_y_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='Pagado',
            field=models.BooleanField(default=0),
        ),
    ]
