# Generated by Django 4.2.1 on 2024-06-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0029_boletas_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='Region',
            field=models.CharField(choices=[('AMN', 'América del Norte'), ('AMS', 'América del Sur'), ('EUR', 'Europa'), ('AFR', 'África'), ('ASI', 'Asia'), ('OCE', 'Oceanía')], max_length=50),
        ),
    ]
